version: '3'
services:
  bijouta:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8080
    container_name: bijouta
    environment:
      DB_PORT: 3306
      DB_HOST: mysql
      DB_PASSWORD: bijouta123
      DB_USERNAME: root
      DB_DATABASE: bijouta
    restart: always
    networks:
        - bijouta
  mysql:
#    build: ./mysql/
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: bijouta
      MYSQL_PASSWORD: bijouta123
      MYSQL_ROOT_PASSWORD: bijouta123
      TZ: UTC
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-time-zone=+01:00','--max_allowed_packet=512M']
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    networks:
      - bijouta
    restart: always
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.0.2
      environment:
        - PMA_HOST=mysql
        - UPLOAD_LIMIT= 500M
      networks:
        - bijouta
      ports:
        - "8002:80"
      restart: always

networks:
  bijouta:
    driver: bridge
